language: perl
install:
 - sudo apt-get install subversion xsltproc libxml2-utils docbook-xsl zip fop rsync poppler-utils
 - sudo apt-get install libipc-run-perl libtemplate-perl libfile-slurp-perl libsvn-svnlook-perl libdatetime-perl libdatetime-format-strptime-perl libfilesys-df-perl libsys-cpuload-perl libmime-lite-perl libhtml-parser-perl
script:
 - ./tests/runtests.sh
